### ISSUE TITLE
AWS 403s

### ISSUE THREAD

**Issue by cseeger** [dyep49/Angular-Umpire-Auditor#10]
Example app [Bloomberg](http://www.businessweek.com/graphics/baseballs-worst-call-of-the-day/#/games/date/2015/5/17) is down, likely due to AWS throwing 403s:

`[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (2015-09-02.gif, line 0)`

**Comment by dyep49** [comment]
So that error is thrown when the gif doesn't exist simply because I haven't made/uploaded it. It would probably be a good idea to replace placekitten with something more helpful. However, I'm no longer maintaining that front end as I don't work at Bloomberg anymore. I've been meaning to create a front end independent of Bloomberg, I just haven't gotten around to it.

**Comment by cseeger** [comment]
Gotcha. Is there a live instance of the app up and running somewhere? Or was the Bloomberg URL the only one?

**Comment by dyep49** [comment]
Since spinning up a server at Bloomberg was considered a security threat, the back end has always lived at http://www.umpireauditor.com, which I host myself.
